name: Build Vue and Spring Boot Projects

on:
  push:
    branches:
      - main
    paths:
      - 'vue-frontend/**'
      - 'springboot-backend/**'
      - '.github/workflows/docker-build.yml'

jobs:
  build-vue:
    if: contains(github.event.head_commit.message, '[skip vue]') == false
    name: Build Vue Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for Vue changes
        uses: dorny/paths-filter@v2
        id: vue-changes
        with:
          filters: |
            vue:
              - 'vue-frontend/**'

      - name: Set up Node.js
        if: steps.vue-changes.outputs.vue == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Vue Project
        if: steps.vue-changes.outputs.vue == 'true'
        working-directory: ./vue-frontend
        run: |
          npm install
          npm run build

  build-java:
    if: contains(github.event.head_commit.message, '[skip java]') == false
    name: Build Spring Boot Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for Java changes
        uses: dorny/paths-filter@v2
        id: java-changes
        with:
          filters: |
            java:
              - 'springboot-backend/**'

      - name: Set up JDK and Maven
        if: steps.java-changes.outputs.java == 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'

      - name: Cache Maven dependencies
        if: steps.java-changes.outputs.java == 'true'
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Java JAR
        if: steps.java-changes.outputs.java == 'true'
        working-directory: ./springboot-backend
        run: mvn clean package -DskipTests

      - name: Upload Spring Boot JAR as Artifact
        if: steps.java-changes.outputs.java == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: springboot-backend-jar
          path: springboot-backend/target/admin-0.0.1-SNAPSHOT.jar
